from typing import *
import abc
from PyQt5.QtCore import pyqtSignal, QObject

from threading_manager import ThreadsManager


# =====================================================================================================================
class Signals(QObject):
    signal__tc_result_updated = pyqtSignal()
    signal__tc_details_updated = pyqtSignal()


# =====================================================================================================================
class TestCase(abc.ABC):
    signals: Signals = Signals()

    SKIP: Optional[bool] = None     # access only over CLASS attribute! not instance!!!
    details: Dict[str, Any] = None
    PARALLEL: Optional[bool] = True

    DUT: Any = None
    DESCRIPTION: str = ""
    PROGRESS: int = 0
    STOP_IF_FALSE_RESULT: Optional[bool] = None

    __result: Optional[bool] = None

    def __init__(self, dut: Any):
        super().__init__()
        self.details = {}
        self.DUT = dut

    @property
    def result(self) -> Optional[bool]:
        return self.__result

    @result.setter
    def result(self, value: Optional[bool]) -> None:
        self.__result = value
        self.signals.signal__tc_result_updated.emit()

    @classmethod
    @property
    def name(cls):
        return cls.__name__

    @classmethod
    def startup_all(cls) -> bool:
        """before batch work
        """
        return True

    def startup(self) -> bool:
        self.PROGRESS = 1
        return True

    def teardown(self):
        self.PROGRESS = 100

    @classmethod
    def teardown_all(cls):
        pass

    def dump_results(self):
        pass

    def run(self) -> None:
        if self.startup():
            self.result = self.run_wrapped()
        self.teardown()

    def add_details(self, details: Dict[str, Any]) -> None:
        self.details.update(details)
        self.signals.signal__tc_result_updated.emit()

    # -----------------------------------------------------------------------------------------------------------------
    @abc.abstractmethod
    def run_wrapped(self) -> bool:
        pass


# =====================================================================================================================
class DutWithTp:
    PRESENT: Optional[bool] = None
    TP_RESULTS: Dict[Type[TestCase], TestCase] = None   # dict is convenient!!!

    check_present: Callable[..., bool]

    def mark_present(self) -> None:
        self.PRESENT = self.check_present()

    def check_result_final(self) -> Optional[bool]:
        for tc in self.TP_RESULTS.values():
            if tc.SKIP:
                continue
            if not tc.result:
                return tc.result
        return True


# =====================================================================================================================
class ManagerTp(abc.ABC):
    TCS: Dict[Type[TestCase], Optional[bool]] = None    # settings
    # {
    #     TC1: True,
    #     TC2: True
    # }
    DUTS: List[DutWithTp] = None    # autogenerated
    # [
    #     Dut1,
    #     Dut2
    # ]

    def __init__(self):
        self.reinit()

    def reinit(self) -> None:
        self.DUTS = []
        self.TCS_apply_skipped()

        self.duts_generate()
        self.duts_mark_presented()
        self.duts_results_init()

    def reinit_new_TCS(self, tcs: Dict[Type[TestCase], Optional[bool]]) -> None:
        self.TCS = tcs
        self.reinit()

    # TCS -----------------------------------------------------------
    def TCS_apply_skipped(self):
        for tc, using in self.TCS.items():
            tc.SKIP = not using

    # DUTS -----------------------------------------------------------
    @abc.abstractmethod
    def duts_generate(self) -> None:
        pass

    def duts_mark_presented(self) -> None:
        for dut in self.DUTS:
            dut.mark_present()

    def duts_results_init(self) -> None:
        for dut in self.DUTS:
            dut.TP_RESULTS = dict()
            for tc in self.TCS:
                dut.TP_RESULTS.update({tc: tc(dut)})

    # RUN -----------------------------------------------------------
    def run(self) -> None:
        for tc in self.TCS:
            if tc.SKIP:
                continue
            if not tc.startup_all():
                continue

            ThreadsManager().thread_items__clear()
            for dut in self.DUTS:
                if dut.PRESENT:
                    if tc.PARALLEL:
                        ThreadsManager().decorator__to_thread(dut.TP_RESULTS[tc].run)()
                    else:
                        dut.TP_RESULTS[tc].run()

            if tc.PARALLEL:
                ThreadsManager().wait_all()
            tc.teardown_all()


# =====================================================================================================================
